### ISSUE TITLE
Get your website design from somewhere else

### ISSUE THREAD

**Issue by S-B99** [national/national.github.io#1]
be a bit more original please

**Comment by wine** [comment]
i made this, ive never looked at ur account

**Comment by S-B99** [comment]
Lol ok right

**Comment by 0-x-2-2** [comment]
@S-B99

Clearly your website is not original: 
![image](https://user-images.githubusercontent.com/9968651/64057657-8f720980-cb6d-11e9-958d-bcf61f043121.png) 
![image](https://user-images.githubusercontent.com/9968651/64057661-96008100-cb6d-11e9-9b24-b495f238ac76.png)

Thank you for reading 
-Christofer Beres

**Comment by wine** [comment]
@S-B99 lololololol paster

**Comment by wine** [comment]
löl
